### ISSUE TITLE
feat: Prompt user on config overwrite for `webpack setup`

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#329]
In 0.21.0.beta4:

It's cool I can run the `webpack setup` command and get a brand-new config, but I was startled that it force-overwrote an existing `webpack.config.js` from a previous BT version. Maybe we should add a confirmation step?

**Comment by ayushn21** [comment]
I did think about doing that ... but I figured the changes will be in git so they'll be super easy to rollback as they won't have been committed. I've also mentioned that the file will be overwritten in my release blog post. 

The `setup` command is just something existing users will run once and new users will never run, so I thought I'd leave out the additional confirmation step since it's so easy to undo.

**Comment by jaredcwhite** [comment]
Makes sense!
