### ISSUE TITLE
Tailwind doesn't work when we use yarn deploy

### ISSUE THREAD

**Issue by work-leonid** [bridgetownrb/bridgetown#356]
This error has already been [discussed](https://github.com/bridgetownrb/bridgetown/issues/333). But the error is still there. 

The problem is caused by the postcss plugin [postcss-focus-within](https://github.com/csstools/postcss-focus-within). Bridgetown uses version 3.0.0 of this plugin. In April there was an update of this package to 4.0.0. With a fix "Fixed: Allow :focus-within to appear escaped in a selector".

I suggest to either update the plugin inside of Bridgetown. Or when installing Tailwind add in `package.json` 
```
"resolutions": {
    "postcss-focus-within": "^4.0.0"
  }
```
That way we'll be using the up-to-date version of the plugin and the error will disappear.

**Comment by ayushn21** [comment]
Honestly, I'm a little reluctant to fix something I consider to be Tailwind's problem within Bridgetown. I totally get your intent with this change and it definitely makes for a smoother DX in the short term.

But in my view, we're adding the Tailwind package, not the `postcss-focus-within` package. Tailwind should be pulling in the correct versions of the dependencies it needs to work. 

I'm not a Tailwind user so I wonder if you have any idea about how widespread this issue is outside of a Bridgetown context and what the "official" workaround or fix for it is? Based on the official Tailwind recommendation we could figure a way to proceed.

**Comment by work-leonid** [comment]
I think this is not a tailwind problem. According to this  [discussion](https://github.com/csstools/postcss-focus-within/issues/3)  this is a postcss problem. Or maybe even `postcss-preset-env`.

**Comment by ayushn21** [comment]
Yeah you're right, it's a `postcss-preset-env` problem. There's been a PR open for over a year to update it <sigh>
https://github.com/csstools/postcss-preset-env/pull/172

Let's sort this out within Bridgetown.

We need to add the the block you posted above to our `package.json.erb` when the `use-postcss` option is set. And we need to run `yarn set resolution postcss-focus-within:^4.0.0` in the `bridgetown webpack enable-postcss` command.

I can put together a PR later this week, or if you fancy giving it a go, you're more than welcome :)

**Comment by work-leonid** [comment]
>I can put together a PR later this week

Please. To be honest, I don't fully understand what needs to be done and how to do it. :)
Thank you!
