### ISSUE TITLE
Deprecate generators in plugins prior to 1.0

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#370]
The "generate" step in Bridgetown is superfluous. Adding either a post_read or pre_render hook accomplishes exactly the same thing. All a generator "does" is get called by the site build in between post_read and pre_render.

Either we should sunset this API in favor of Builders + Hooks, or we should expand the generator API in some fashion so it offers more utility. Will give this a bit of thought. Comments and suggestions most welcome!

**Comment by jaredcwhite** [comment]
Part of this would be to refactor existing generators within our codebase to use hooks instead￼.

Speaking of hooks, should we also rename those to callbacks? I don't actually know why they're called hooks other than I think that's what a similar concept was called in WordPress originally￼.

**Comment by ayushn21** [comment]
Personally I quite like the term `generator`. It denotes that a block is playing a role in the generation of a website. For example, on my photo gallery site (https://fslash42.com); I've got a builder that generates a page for each photo and photo album based on data files; so that looks like:

```
    generator do
      site.data.albums.each do |album|
        site.generated_pages << AlbumPage.new(site, album)

        album.photos.each_with_index do |photo, index|
          site.generated_pages << PhotoPage.new(site, album, photo, index)
        end
      end
```

In terms of readability, I reckon that is more descriptive than:

```
    hook :site, :post_read do
      site.data.albums.each do |album|
        site.generated_pages << AlbumPage.new(site, album)

        album.photos.each_with_index do |photo, index|
          site.generated_pages << PhotoPage.new(site, album, photo, index)
        end
      end
```

Even if does nothing special, I think it's worth keeping just for the readability aspect. 

Re `hooks` or `callbacks`; I prefer `hooks` but don't really have much of an opinion on it and wouldn't be bothered either way. Only thing I'd say is I think we should invest effort in only changing things that really need changing. I'm not sure a rename to `callbacks` would add enough value to justify the effort 🤷‍♂️

**Comment by jaredcwhite** [comment]
Hey @ayushn21, somehow I totally missed seeing this comment way back when. You convinced me! Closing. ☺️
