### ISSUE TITLE
feat: Support additional template engines (slim, haml, ERB, etc.)

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#42]
Adding this at the behest of @svoop to request investigation of what it would take to support new template engines. There were attempts in the past to try adding support to Jekyll for other templates, but it was sort of janky and Liquid was still involved sometimes which seems…weird…so maybe we can give it a fresh look.

Full disclosure: this isn't a feature I'm personally chomping at the bit for, but I obviously want to do right by the community. If you have strong feelings on the subject, please chime in folks! 😃

**Comment by svoop** [comment]
Thanks for picking up this topic, @jaredcwhite. There are two quite distinct use cases:

* Site content is maintained by non-tech untrusted folks (e.g. marketing agency): Liquid is a good choice since it makes it hard to break something bad or to introduce security issues. However, it comes at the price of a somewhat cumbersome syntax which has to be learned.
* Site content is maintained by tech-savvy trusted folks (e.g. software project): ERB or Slim are more powerful and easier to maintain. Also less context switching.

I guess it boils down to how much work it would be to decouple Bridgetown from Liquid. Certainly a nice to have, for some people (like me) maybe a deal breaker. But there are other SSG to chose from, so certainly not the most important feature on the list.

Not sure how many people come across this issue, but just in case, cast your vote below please:

👍 = important to me / 👎 = not important to me

**Comment by jaredcwhite** [comment]
Will get closed by #79
