### ISSUE TITLE
docs: remove deprecated plugin from list

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown#496]
## Motivation

https://edge.bridgetownrb.com/plugins/ still mentions https://github.com/andrewmcodes/bridgetown-inline-svg, but according to the repo `This gem has been replaced by [ayushn21/bridgetown-svg-inliner](https://github.com/ayushn21/bridgetown-svg-inliner) and will not be receiving further updates.`

## Suggestion

Maybe less confusing if only the one existed on the plugin list (ie `ayushn21/bridgetown-svg-inliner`)

**Comment by jaredcwhite** [comment]
Thanks for the suggestion @stevegeek! The plugins page is autogenerated by filtering through GitHub tags, and it does leave off any archived repos. So perhaps you could suggest the repo owner (@andrewmcodes) archive the project. Otherwise, I'd have to start maintaining a separate list of plugins to take out, which isn't ideal.

**Comment by andrewmcodes** [comment]
@jaredcwhite I hadn't archived it in case anyone was still using it but I am happy to go ahead and do that. 

Could also filter out if they have the tag `bridgetown-legacy` or something in the future 🤔

**Comment by andrewmcodes** [comment]
[andrewmcodes/bridgetown-inline-svg](https://github.com/andrewmcodes/bridgetown-inline-svg) has been archived in favor of [ayushn21/bridgetown-svg-inliner](https://github.com/ayushn21/bridgetown-svg-inliner) so that should resolve this issue.
