### ISSUE TITLE
Coming 6/29 —Rename the default branch name

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#77]
As benevolent dictator (😉) of Bridgetown, I'm planning on renaming the default branch name away from `master`. I'm open to suggestions, whether we go with `main` or `trunk` or something along those lines. `main` seems to be what a lot of folks are going with.

Also found this neat gist (requires latest GH CLI version) to make the switchover easy:
https://gist.github.com/mislav/5ac69530acbe1b4ca909e272caabfdba

**Comment by jaredcwhite** [comment]
Got a great suggestion from @andrewmcodes on Twitter: `base`

Base your branch off of `base`

**Comment by jaredcwhite** [comment]
From boramacz' tweet:

> Yes, and "rebasing" seems to fit nicely, too!

**Comment by king601** [comment]
I much prefer `main` in this discussion if we're honest. base feels confusing esp when you go to make a PR and it asks you the base branch. Seems redundant for it to be `base: base` when opening PRs. 

base of what?

It may be too early to tell what other projects are doing to find the new 'standard' branch but my two cents leads me to believe main is going to win out... because it's similar enough to what we're used to, and describes the primary branch without the negative history... Base can fit the bill too, but I've seen more adoption of `main` than other words floating out there.

That said, I don't have a true fight here, I haven't contributed code (yet, hopefully someday!) so take that with what you will :)

**Comment by king601** [comment]
Just some more info, it looks like Rspec is leaning towards `main` as well; https://rspec.info/blog/2020/06/rspec-branching-strategy/

**Comment by jaredcwhite** [comment]
Yeah, main seems like the likely candidate at this point… primarily since it may become the new "standard" if you will and it makes sense to go in that direction.

**Comment by jaredcwhite** [comment]
OK, I am planning to change the default branch to `main` on Monday, June 29. Please plan to update your remotes accordingly! 🙏

**Comment by jaredcwhite** [comment]
All right, the change has been made. If you've checked out the Bridgetown repo locally, you should be able to edit your `.git/config` file and replace `master` with `main`. If you reference the repo directly in your `Gemfile`, you'll probably need to add a `branch:` option and specify `main`. If you run into any other issues, please let me know!
