### ISSUE TITLE
Netlify bundled configuration issues

### ISSUE THREAD

**Issue by jclusso** [bridgetownrb/bridgetown#823]
I'm using Netlify and noticed some issues that I wanted to bring up because I'm not sure about them. The CSS and JS path appear to be wrong. My CSS and JS do not appear to be nested in a `css` and `js` folder, but rather directly in the `static` folder. (ex: `output/_bridgetown/static/`)

https://github.com/bridgetownrb/bridgetown/blob/9b769d55fa47db515a62af338b5fc3281212d1c0/bridgetown-core/lib/bridgetown-core/configurations/netlify/netlify.sh#L6-L7

Additionally, my build does not appear to have a `NETLIFY_IMAGES_CDN_DOMAIN` and I was wondering where this came from. I can't find much about this.

https://github.com/bridgetownrb/bridgetown/blob/9b769d55fa47db515a62af338b5fc3281212d1c0/bridgetown-core/lib/bridgetown-core/configurations/netlify/netlify.sh#L14

@ayushn21 maybe you can provide some insight since I saw you authored this.

**Comment by ayushn21** [comment]
> my build does not appear to have a `NETLIFY_IMAGES_CDN_DOMAIN`

I'm pretty sure I stole this from somewhere else .... can't remember where now, it's been a while since I used Netlify. I'll take a peek at your PR ... should be all good I think, this configuration hasn't been updated in ages so not surprising something's broken.

**Comment by jclusso** [comment]
> > my build does not appear to have a `NETLIFY_IMAGES_CDN_DOMAIN`
> 
> I'm pretty sure I stole this from somewhere else .... can't remember where now, it's been a while since I used Netlify. I'll take a peek at your PR ... should be all good I think, this configuration hasn't been updated in ages so not surprising something's broken.

The only place I could find it was a few random other projects on GitHub which leads me to believe it must have existed at some point. It's not in my Netlify builds which is how I found out so they must've removed it.

**Comment by ayushn21** [comment]
Oh yeah it definitely existed. I used to host all my sites on netlify
which is why I wrote this configuration. 

I’ve moved everything to render.com now so haven’t kept up to date with
Netlify’s updates… 


On November 2, 2023, GitHub Notification ***@***.***>
wrote:
> > > my build does not appear to have a NETLIFY_IMAGES_CDN_DOMAIN
> > >
> >
> > I'm pretty sure I stole this from somewhere else .... can't remember
> > where now, it's been a while since I used Netlify. I'll take a peek
> > at your PR ... should be all good I think, this configuration hasn't
> > been updated in ages so not surprising something's broken.
> >
>
> The only place I could find it was a few random other projects on
> GitHub which leads me to believe it must have existed at some point.
> It's not in my Netlify builds which is how I found out so they must've
> removed it.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/bridgetownrb/bridgetown/issues/823#issuecomment-
1791538555>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/ABFSFB4YRGGSQAXO3CBKWC3YCQDQVAVCNFSM6AAAAAA63KB2M2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJRGUZTQNJVGU>.
You are receiving this because you were mentioned.Message ID:
***@***.***>
